### PR TITLE
Fix fetching of temp_sw in example.py

### PR DESCRIPTION
**Pull request by stilllman**
The result I get when calling `get_config` is layouted like this:
`{'sensors': [{'id': 'temp_sw', 'value', '60', ...}, ...], ...}`

@foreign-sub Can you confirm you have the same?

### CODE REVIEW

**Comment by foreign-sub** [comment]
yes, before switching to API v6, you had:

> System Config V5 (DEPRECATED)

SystemConfigV5 has the following attributes:

SystemConfigV5

....

    temp_cpum int Read-only

        temp cpum (°C)

    temp_sw int Read-only

        temp sw (°C)

    temp_cpub int Read-only

        temp cpub (°C)

    fan_rpm int Read-only

        fan rpm

Now with API v6:
> System Config

SystemConfig has the following attributes:

SystemConfig

....

SystemConfigSensor

    id string Read-only

        sensor id

    name string Read-only

        sensor display name

    value int Read-only

        sensor current value (in celsius degree)

SystemConfigFan

    id string Read-only

        fan id

    name string Read-only

        fan display name

    value int Read-only

        fan current speed (RPM)

**Comment by stilllman** [comment]
Hmm, this confirms my intuition that the API version should be hard-coded, either in `aiofreepybox` or on the client side. Otherwise, scripts written against version `v<N>` could stop working as soon as the Freebox is updated to `v<N+1>` :/

**Comment by foreign-sub** [comment]
The way i see it, they only support the 'current' version whatever it is. In this particular case i guess they really had no other choice than to rework the schema to support more features with some impact on rrd data also. There is no telling if this may or may not happen again in the future, but i believe this to be an exception.

**Comment by foreign-sub** [comment]
The only way i see to prevent any surprises is to lock the API to (current) v6 and force downgrade any newer/higher versions until it is tested to be compatible.

**Comment by SNoof85** [comment]
@stilllman what do you think about this ? I have some ongoing changes into home assistant and don't want to work it twice. I'm waiting that you release a new version of aiofreepybox then ;)

**Comment by stilllman** [comment]
@SNoof85 I think that the solution proposed by @foreign-sub is the best we can have without rewriting the entire library, as it allows both "use frozen api" and "use latest available api". Since the API version is frozen in home assistant, things should be good.

Why do you want a new release for home assistant? Do you want to integrate some new features? The auto detection is not merged yet unfortunately, is is something else that you would like to use?

**Comment by SNoof85** [comment]
@stilllman i have some pending requests about the Freebox integration (mainly on home API) and few more sensors. As i would like also switch to API V6 i'll have some work again to do and this is not really easy to test without a new release (have to clone the repo and i'm not very easy with git commands 👎 )

**Comment by foreign-sub** [comment]
Current open PR's cover pretty much everything still missing in the API with some extras, i'm currently working on typing everything but this is only a bonus and also a long and tedious work, so it's not really required to be finished if you want to do a release soon. I'm pretty much done on every PR on a functional basis, i'd say #22 #39 and #43 adds the most value, then #47 #17, then the remaining ones in no particular order.

**Comment by foreign-sub** [comment]
@SNoof85 you can clone my repo with:
git clone https://github.com/foreign-sub/aiofreepybox.git in any dir you like
then switch between branches with:
git checkout branch-name
ex : git checkout add-fbx-detect
or you can also do something like:
git checkout aiofreepybox
then:
git merge add-fbx-detect
git merge ...
merge in any branch you like then copy the directory in the HA afpbx folder.
Just delete the directory when you're done or restart if you want to reset on an updated version.

**Comment by SNoof85** [comment]
This is not a repo problem, home assistant uses pypi packages 😄 that's why i asked to get a release (it was a pypi release).

**Review by SNoof85 — APPROVED** [review]

**Comment by SNoof85** [comment]
This one can be merged as soon as we clearly state that API version used must be >=6

**Pull request closed without merging**
